version: '3'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trading_bitcoin
      MYSQL_USER: trading_bitcoin
      MYSQL_PASSWORD: trading_bitcoin
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "./docker/mysql/multibyte.cnf:/etc/mysql/conf.d/multibyte.cnf"

  golang:
    container_name: golang
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    tty: true
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/trading_bitcoin_api
    # command: go run main.go

volumes:
  mysql-data:
